name: construction
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.1.1
  bloc: ^8.1.0
  firebase_core: ^3.2.0
  firebase_auth: ^5.1.2
  cloud_firestore: ^5.1.0
  firebase_storage: ^12.1.1
  image_picker: ^1.1.2
  dropdown_button2: ^2.3.9
  bot_toast: ^4.0.3
  hive: ^2.2.3
  dio: ^5.5.0+1
  iconify_flutter: ^0.0.5
  flutter_local_notifications: ^17.2.1+1
  carousel_slider: ^4.1.1
  firebase_cached_image: ^0.6.1
  carousel_indicator: ^1.0.6
  flutter_animation_progress_bar: ^2.3.1
  intl: ^0.19.0
  syncfusion_flutter_pdf: ^26.1.41
  syncfusion_flutter_signaturepad: ^26.1.41
  path_provider: ^2.0.11
  open_filex: ^4.3.2
  toggle_switch: ^2.0.1
 


dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^4.0.0



flutter:


  uses-material-design: true


  assets:
    - assets/images/
    - assets/icons/

  
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700

