// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB2N0d_iLi5FML1aK6S03DdJgujoa2d6zU',
    appId: '1:659233249949:web:844bab3ba2ffeff73d9274',
    messagingSenderId: '659233249949',
    projectId: 'constuction-aakar',
    authDomain: 'constuction-aakar.firebaseapp.com',
    storageBucket: 'constuction-aakar.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBC4QgZNq9hHKT597KakV33iP33j66JQNk',
    appId: '1:659233249949:android:6a5eb3e3b6e9f8193d9274',
    messagingSenderId: '659233249949',
    projectId: 'constuction-aakar',
    storageBucket: 'constuction-aakar.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDc6HdudAFwTxRKyALxBiKfYTnNN6dQRaA',
    appId: '1:659233249949:ios:5ceaa7c7f97413543d9274',
    messagingSenderId: '659233249949',
    projectId: 'constuction-aakar',
    storageBucket: 'constuction-aakar.appspot.com',
    iosClientId: '659233249949-pbirdhcp9r4il0p7ntnlipf5q7133dis.apps.googleusercontent.com',
    iosBundleId: 'com.aakar.construction',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDc6HdudAFwTxRKyALxBiKfYTnNN6dQRaA',
    appId: '1:659233249949:ios:5ceaa7c7f97413543d9274',
    messagingSenderId: '659233249949',
    projectId: 'constuction-aakar',
    storageBucket: 'constuction-aakar.appspot.com',
    iosClientId: '659233249949-pbirdhcp9r4il0p7ntnlipf5q7133dis.apps.googleusercontent.com',
    iosBundleId: 'com.aakar.construction',
  );
}
