// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB5Qwsl_d3D8oeEaDiFOF9Ii9jkIsa1C9I',
    appId: '1:369677296680:web:a8515e8dbfb0dfddea811d',
    messagingSenderId: '369677296680',
    projectId: 'construction-aakar',
    authDomain: 'construction-aakar.firebaseapp.com',
    storageBucket: 'construction-aakar.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC0xeIhhmbg_79JajDb0TedVTrRTOPbDD4',
    appId: '1:369677296680:android:53ca875955b65dceea811d',
    messagingSenderId: '369677296680',
    projectId: 'construction-aakar',
    storageBucket: 'construction-aakar.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCg0B3VvU_fNaegfLKEDkbAVU8YEYSalX0',
    appId: '1:369677296680:ios:bdf1299d17736d60ea811d',
    messagingSenderId: '369677296680',
    projectId: 'construction-aakar',
    storageBucket: 'construction-aakar.appspot.com',
    iosClientId: '369677296680-tctev1d0gr6lrn97d97anicq6dde6fn9.apps.googleusercontent.com',
    iosBundleId: 'com.mtech.aakar.construction',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCg0B3VvU_fNaegfLKEDkbAVU8YEYSalX0',
    appId: '1:369677296680:ios:bdf1299d17736d60ea811d',
    messagingSenderId: '369677296680',
    projectId: 'construction-aakar',
    storageBucket: 'construction-aakar.appspot.com',
    iosClientId: '369677296680-tctev1d0gr6lrn97d97anicq6dde6fn9.apps.googleusercontent.com',
    iosBundleId: 'com.mtech.aakar.construction',
  );
}
